pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
    - ./node_modules
    volumes:
    - /tmp/cache:/cache
    when:
      event: push

  install:
    image: node:10.13.0-alpine
    commands:
    - yarn
    when:
      event: push

  build:
    image: node:10.13.0-alpine
    commands:
      - yarn run build
    when:
      event: push

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
    - ./node_modules
    volumes:
    - /tmp/cache:/cache
    when:
      event: push

  deploy-dev:
    image: acazacu/drone-plugin-s3-sync:4
    bucket: dev.nvent.nl
    region: eu-central-1
    source: dist
    target: /
    delete: true
    when:
      event: [ push, tag ]
      branch:
        exclude: master

  deploy-prod:
    image: acazacu/drone-plugin-s3-sync:4
    bucket: nvent.nl
    region: eu-central-1
    source: dist
    target: /
    delete: true
    when:
      branch: master
      event: tag